//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language_school
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientService = new HashSet<ClientService>();
            this.Tag = new HashSet<Tag>();
        }
        
        public string fullName
        {
            get
            {
                return $"ID: {this.ID} {this.FirstName} {this.LastName} {this.Patronymic}";
            }
        }
        public string GenderAndData
        {
            get
            {
                return $"Пол: {this.Gender.Name} Дата рождения: {this.Birthday}";
            }
        }
        public string PhoneAndEmail
        {
            get
            {
                return $"Телефон: {this.Phone} e-mail: {this.Email}";
            }
        }
        public string DataRegist
        {
            get
            {
                return $"Дата регистрации: {RegistrationDate.ToShortDateString()}";
            }
        }

        public int CountVisit
        {
            get
            {
                return ClientService.Count;
            }
        }
        public string LasttVisit
        {
            get
            {
                string text = "Дата последнего посещения: ";
                if (ClientService.Count > 0)
                {
                    return  text + ClientService.Max(p => p.StartTime.ToShortDateString());
                }
                else
                    return text + "нет";
            }
        }
        public string lastPole
        {
            get
            {
                return $"{LasttVisit} Количество посещений: {CountVisit}";
            }
        }


        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string GenderCode { get; set; }
        public string Phone { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Email { get; set; }
        public System.DateTime RegistrationDate { get; set; }
    
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tag { get; set; }
    }
}
